############################
## CHANGE THESE
############################

baseURL: "https://devanshimirchandani.github.io/devanshi-github-io"
title: devanshi-github-io

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
